[tool.poetry]
name = "refitt-client"
version = "0.26.1"
description = "REFITT client command-line tool"
readme = "README.rst"
homepage = "https://refitt.org"
documentation = "https://refitt.readthedocs.io"
repository = "https://github.com/refitt/refitt"
authors = [
    "Dan Milisavljevic <dmilisav@purdue.edu>",
    "Niharika Sravan <nsravan@purdue.edu>",
    "Geoffrey Lentner <glentner@purdue.edu>",
    "Mark Linvill <mlinvill@purdue.edu>",
    "Bhagya Subrayan <bsubraya@purdue.edu>",
    "Katie Weil <keweil@purdue.edu>",
    "Josh Church <church10@purdue.edu>",
    "John Banovetz <jbanovet@purdue.edu>",
]
maintainers = [
    "Geoffrey Lentner <glentner@purdue.edu>"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Astronomy",
    "License :: OSI Approved :: Apache Software License",
]
packages = [{include = "refitt", from = "src"}]

[tool.poetry.scripts]
refitt-client = "refitt.client:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
refitt-core = "^0.26.1"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
refitt-core = {path = "../../libs/refitt-core", develop = true}
pytest = "^7.3.2"
hypothesis = "^6.78.2"
ipython = "^8.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = ["--strict-markers", ]
markers = [
    "unit: Unit tests are short, interface driven tests on discrete components.",
    "integration: Integration tests are often longer and deal with the interaction between systems.",
    "parameterize: Place holder for parameterized tests (not a real type).",
]
