[tool.poetry]
name = "refitt-core"
version = "0.26.1"
description = "REFITT core package"
readme = "README.rst"
homepage = "https://refitt.org"
documentation = "https://refitt.readthedocs.io"
repository = "https://github.com/refitt/refitt"
authors = [
    "Dan Milisavljevic <dmilisav@purdue.edu>",
    "Niharika Sravan <nsravan@purdue.edu>",
    "Geoffrey Lentner <glentner@purdue.edu>",
    "Mark Linvill <mlinvill@purdue.edu>",
    "Bhagya Subrayan <bsubraya@purdue.edu>",
    "Katie Weil <keweil@purdue.edu>",
    "Josh Church <church10@purdue.edu>",
    "John Banovetz <jbanovet@purdue.edu>",
]
maintainers = [
    "Geoffrey Lentner <glentner@purdue.edu>"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Astronomy",
    "License :: OSI Approved :: Apache Software License",
]
packages = [{include = "refitt", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
cmdkit = "^2.7.3"
toml = "^0.10.2"
tomlkit = "^0.12.1"
pyyaml = "^6.0"
rich = "^13.4.2"
requests = "^2.31.0"
cryptography = "^41.0.1"
streamkit = {version = "^0.3.2", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
hypothesis = "^6.78.2"
ipython = "^8.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
