[project]
name = "refitt"
version = "0.26.1"
description = "Recommender Engine for Intelligent Transient Tracking"
readme = "README.rst"
homepage = "https://refitt.org"
documentation = "https://refitt.readthedocs.io"
repository = "https://github.com/refitt/refitt"
authors = [
    { name = "Dan Milisavljevic", email = "dmilisav@purdue.edu" },
    { name = "Niharika Sravan", email = "nsravan@purdue.edu" },
    { name = "Geoffrey Lentner", email = "glentner@purdue.edu" },
    { name = "Mark Linvill", email = "mlinvill@purdue.edu" },
    { name = "Bhagya Subrayan", email = "bsubraya@purdue.edu" },
    { name = "Katie Weil", email = "keweil@purdue.edu" },
    { name = "Josh Church", email = "church10@purdue.edu" },
    { name = "John Banovetz", email = "jbanovet@purdue.edu" },
    { name = "Danielle Dickinson", email = "dickinsd@purdue.edu" }
]
maintainers = [
    { name = "Geoffrey Lentner", email = "glentner@purdue.edu" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Astronomy",
    "License :: OSI Approved :: Apache Software License",
]
requires-python = ">=3.12"
dependencies = [
    "refitt-core",
    "refitt-data",
    "refitt-api",
    "refitt-assets",
    "refitt-client",
    "refitt-server",
    "refitt-broker",
    "refitt-tns",
    "refitt-admin",
]
#matplotlib = "^3.7.1"
#seaborn = "^0.13.0"
#astroplan = "^0.10.0"
#timezonefinder = "^6.2.0"
#pytz = "^2024.1"
#bs4 = "^0.0.2"
#jinja2 = "^3.1.2"
#tables = "^3.8.0"

[dependency-groups]
dev = [
    "pytest>=8.1.1",
    "hypothesis>=6.100.0",
    "ipython>=8.14.0",
    "pytest-cov>=4.1.0",
    "line-profiler>=4.0.3",
    "memory-profiler>=0.61.0",
]
docs = [
    "sphinx>=7.2.6",
    "sphinx-sitemap>=2.5.1",
    "sphinx-autobuild>=2024.2.4",
    "sphinx-copybutton>=0.5.2",
    "sphinxext-opengraph>=0.9.1",
    "sphinxcontrib-details-directive>=0.1.0",
    "sphinx-toolbox>=3.5.0",
    "sphinx-inline-tabs>=2023.4.21",
    "enum-tools[sphinx]>=0.12.0",
    "furo>=2024.1.29",
    "setuptools>=75.8.2",
]

[tool.uv.workspace]
members = [
    "py/libs/*",
    "py/apps/*",
]
exclude = ['py/apps/refitt-phot']

[tool.uv.sources]
refitt-core = { workspace = true }
refitt-data = { workspace = true }
refitt-api = { workspace = true }
refitt-assets = { workspace = true }
refitt-client = { workspace = true }
refitt-server = { workspace = true }
refitt-broker = { workspace = true }
refitt-tns = { workspace = true }
refitt-admin = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/refitt"]

[tool.uv]
default-groups = ["dev", "docs"]

[tool.pytest.ini_options]
addopts = ["--strict-markers", ]
markers = [
    "unit: Unit tests are short, interface driven tests on discrete components.",
    "integration: Integration tests are often longer and deal with the interaction between systems.",
    "parameterize: Place holder for parameterized tests (not a real type).",
]
