[tool.poetry]
name = "refitt"
version = "0.12.2"
description = "Recommender Engine for Intelligent Transient Tracking"
authors = ["Geoffrey Lentner, M.Sc. <glentner@purdue.edu>",
           "Dan Milisavljevic, Ph.D. <dmilisav@purdue.edu>",
           "Niharika Sravan, Ph.D. <nsravan@purdue.edu>",
           "Mark Linvill <mlinvill@purdue.edu>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "3.8.7"
SQLAlchemy = "^1.3.23"
psycopg2 = "^2.8.6"
Flask = "^1.1.2"
gunicorn = "^20.0.4"
rich = "^9.11.1"
tqdm = "^4.57.0"
toml = "^0.10.2"
cmdkit = "^2.2.3"
streamkit = "^0.3.2"
antares-client = "^1.0.4"
slackclient = "^2.9.3"
names-generator = "^0.1.0"
matplotlib = "^3.3.4"
seaborn = "^0.11.1"
requests = "^2.25.1"
cryptography = "^3.4.6"
astropy = "^4.2"
numpy = "^1.19.5"
scipy = "^1.6.1"
pandas = "^1.2.2"
pyarrow = "^3.0.0"
tensorflow = "^2.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
hypothesis = "^6.3.1"
ipython = "^7.20.0"
twine = "^3.3.0"
Sphinx = "^3.5.1"
pydata-sphinx-theme = "^0.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
