name: Run tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Configure poetry
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Install virtual environment
        run: poetry install

      - name: Run tests
        env:
          REFITT_LOGGING_LEVEL: DEBUG
          REFITT_DATABASE_FILE: test.db
          REFITT_API_SITE: localhost
          REFITT_API_PORT: 5050
          REFITT_API_ROOTKEY: ${{ secrets.API_ROOTKEY_FAKE }}
        run: |
          poetry run refitt database init --test
          poetry run refitt service api start --workers 1 --port 5050 &
          sleep 5
          poetry run pytest -v

      - name: Publish package to test repository
        run: poetry publish --build -r testpypi
