name: tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Refitt
      run: |
        python -m pip install --upgrade pip setuptools wheels
        python -m pip install pipenv
        pipenv install --deploy --system

    - name: Boostrap Database, Start API, Run All Tests
      env:
        REFITT_LOGGING_LEVEL: DEBUG
        REFITT_DATABASE_BACKEND: sqlite
        REFITT_DATABASE_FILE: /var/lib/refitt/database.sqlite
        REFITT_API_SITE: localhost
        REFITT_API_PORT: 5000
        REFITT_API_ROOTKEY: ${{ secrets.API_ROOTKEY_FAKE }}
      run: |
        mkdir -p /var/lib/refitt
        refitt database init --drop --test
        refitt service api start --workers 1 --port 5000 &
        sleep 5
        pytest -v
